sudo: required
language: node_js
node_js:
  - 10

os:
  - windows
  - linux
  - osx

before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" == "windows" ]; then
      curl -L -o ubuntu-1804.zip https://aka.ms/wsl-ubuntu-1804
      powershell.exe -NoProfile -Command "Expand-Archive -Path ubuntu-1804.zip -DestinationPath Ubuntu"
      Ubuntu/ubuntu1804.exe install --root
      wsl curl -sL https://deb.nodesource.com/setup_10.x "|" sudo -E bash -
      wsl sudo apt-get install -y nodejs
    fi

script:
  - |
    if [ "${TRAVIS_OS_NAME}" == "windows" ]; then
      wsl npm run unit
    else
      npm test
    fi

after_success:
  - npm run report-coverage
